### PR TITLE
Remove no index search feature flag

### PR DESCRIPTION
**Pull request by lindenmckenzie**
### What

Removed no index search feature flag and set to true. 

### How to review

Check release ok. 

### Who can review

Not me.

### CODE REVIEW

**Comment by cookel2** [comment]
Linden, my understanding is that we shouldn't create release branches into master until we've first created a feature branch, which has been tested in sandbox? Forgive me if I'm incorrect.

**Comment by lindenmckenzie** [comment]
@cookel2 yeah that's right - I did that 😄 see this PR: https://github.com/ONSdigital/dp-frontend-search-controller/pull/247

**Review by cookel2 — APPROVED** [review]
looks good to me 👍

**Comment by cookel2** [comment]
> @cookel2 yeah that's right - I did that 😄 see this PR: #247

Thanks Linden 👍

**Pull request merged**
